name: Deploy to prod

on: 
  pull_request:
      branches: ["develop"]

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: prod
      aws-assume-role-arn: "arn:aws:iam::710271919573:role/github-actions-l-furquim"
      aws-region: "us-east-1"
      aws-state-s3-bucket: "tfstate-710271919573"
      aws-lock-dynamodb-table: "terraform-lock"
      destroy: false
