name: Deploy to dev

on: 
  push:
    branches: ["develop"]

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: dev
      aws-region: "us-east-1"
      destroy: true 
    secrets:
      AWS_ASSUME_ROLE_ARN: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
      AWS_STATE_S3_BUCKET: ${{ secrets.AWS_STATE_S3_BUCKET }}
      AWS_LOCK_DYNAMODB_TABLE: ${{ secrets.AWS_LOCK_DYNAMODB_TABLE }}

  ecs-build-deploy:
    if: true
    uses: ./.github/workflows/ecs.yml
    with:
      environment: dev
      aws-region: "us-east-1"
      cluster-name: instant-term-cluster
    secrets:
      AWS_ASSUME_ROLE_ARN: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
