name: Deploy to dev

on: 
  pull_request:
      branches: ["main"]

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: dev
      aws-region: "us-east-1"
      aws-assume-role-arn: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
      aws-state-s3-bucket: ${{ secrets.AWS_STATE_S3_BUCKET }}
      aws-lock-dynamodb-table: ${{ secrets.AWS_LOCK_DYNAMODB_TABLE }}
      destroy: false
    secrets: inherit

  ecs-build-deploy:
    name: Build and Deploy to Dev
    needs: terraform
    if: true # alterar para destroy ou nao
    uses: ./.github/workflows/ecs.yml
    with:
      environment: dev
      aws-region: us-east-1
      cluster-name: instant-term-dev
      aws-assume-role-arn: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
    secrets:
      AWS_ASSUME_ROLE_ARN: ${{ secrets.AWS_ASSUME_ROLE_ARN }}

